//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.15 at 05:36:59 PM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://munis.ws.uz", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uz.ws.munis;
